logging:
  level:
    root: debug
spring:
  profiles:
    active: dev
  sql:
    init:
      schema-locations: classpath:import.sql
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      db-type: mysql
mybatis:
  type-aliases-package: com.example.mybaitsmapper
  mapper-locations: classpath:META-INF/mappings/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 500
    default-statement-timeout: 80
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
